[project]
authors = ["Bernardo Taveira <taveira@student.chalmers.se>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge",
]
name = "mojosplat"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
python = ">=3.12.0,<3.13"
numpy = ">=2.2.5,<3"

[pypi-dependencies]
torch = ">=2.7.0, <3"
pillow = ">=11.2.1, <12"
